use_frameworks!

target 'CountDownLabel_Example' do
  pod 'CountDownLabel', :path => '../'

  target 'CountDownLabel_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  end
end
